
-- Add missing columns to NCDRiskAssessments table

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'CancerMedication')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD CancerMedication NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'CancerYear')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD CancerYear NVARCHAR(4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'CivilStatus')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD CivilStatus NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'DiabetesMedication')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD DiabetesMedication NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'DiabetesYear')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD DiabetesYear NVARCHAR(4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryCancerFather')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryCancerFather BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryCancerMother')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryCancerMother BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryCancerSibling')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryCancerSibling BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryDiabetesFather')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryDiabetesFather BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryDiabetesMother')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryDiabetesMother BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryDiabetesSibling')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryDiabetesSibling BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryHeartDiseaseFather')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryHeartDiseaseFather BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryHeartDiseaseMother')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryHeartDiseaseMother BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryHeartDiseaseSibling')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryHeartDiseaseSibling BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryLungDiseaseFather')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryLungDiseaseFather BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryLungDiseaseMother')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryLungDiseaseMother BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryLungDiseaseSibling')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryLungDiseaseSibling BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryOther')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryOther NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryOtherFather')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryOtherFather BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryOtherMother')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryOtherMother BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryOtherSibling')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryOtherSibling BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryStrokeFather')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryStrokeFather BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryStrokeMother')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryStrokeMother BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FamilyHistoryStrokeSibling')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FamilyHistoryStrokeSibling BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'FirstName')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD FirstName NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'HypertensionMedication')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD HypertensionMedication NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'HypertensionYear')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD HypertensionYear NVARCHAR(4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'LastName')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD LastName NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'LungDiseaseMedication')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD LungDiseaseMedication NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'LungDiseaseYear')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD LungDiseaseYear NVARCHAR(4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_NAME = 'MiddleName')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD MiddleName NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NCDRiskAssessments' AND COLUMN_name = 'Occupation')
BEGIN
    ALTER TABLE NCDRiskAssessments ADD Occupation NVARCHAR(100) NULL;
END
