-- Direct SQL script to fix HEEADSSS column sizes
-- Run this directly against your Azure SQL Database

PRINT 'Starting HEEADSSS column size fixes...'

-- Fix Is4Ps column (the main problematic column)
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'Is4Ps')
BEGIN
    PRINT 'Fixing Is4Ps column...'
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN Is4Ps NVARCHAR(MAX)
    PRINT 'Is4Ps column fixed successfully'
END
ELSE
BEGIN
    PRINT 'Is4Ps column does not exist, adding it...'
    ALTER TABLE HEEADSSSAssessments ADD Is4Ps NVARCHAR(MAX)
    PRINT 'Is4Ps column added successfully'
END

-- Fix other PhilHealth columns
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'IsNHPTS')
BEGIN
    PRINT 'Fixing IsNHPTS column...'
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN IsNHPTS NVARCHAR(MAX)
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'IsPhilHealthBeneficiaryOnly')
BEGIN
    PRINT 'Fixing IsPhilHealthBeneficiaryOnly column...'
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN IsPhilHealthBeneficiaryOnly NVARCHAR(MAX)
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'IsOwnPhilHealth')
BEGIN
    PRINT 'Fixing IsOwnPhilHealth column...'
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN IsOwnPhilHealth NVARCHAR(MAX)
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'PhilHealthPIN')
BEGIN
    PRINT 'Fixing PhilHealthPIN column...'
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN PhilHealthPIN NVARCHAR(MAX)
END

-- Fix other problematic encrypted columns
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'SexualityHealthConcerns')
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityHealthConcerns NVARCHAR(MAX)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'SexualityPartnersCount')
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityPartnersCount NVARCHAR(MAX)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'SexualityPregnancyExperience')
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityPregnancyExperience NVARCHAR(MAX)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'SexualityProtectionUse')
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityProtectionUse NVARCHAR(MAX)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'SexualitySTIExperience')
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualitySTIExperience NVARCHAR(MAX)

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HEEADSSSAssessments' AND COLUMN_NAME = 'SexualityHarassment')
    ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityHarassment NVARCHAR(MAX)

-- Verify the fix
PRINT 'Verifying fix...'
SELECT COLUMN_NAME, DATA_TYPE, 
       CASE WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN 'MAX' 
            ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) 
       END AS COLUMN_SIZE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'HEEADSSSAssessments' 
  AND COLUMN_NAME IN ('Is4Ps', 'IsNHPTS', 'PhilHealthPIN')
ORDER BY COLUMN_NAME

PRINT 'Column size fix completed!'
