-- SQL Script to make HEEADSSSAssessments fields nullable
-- This script should be run directly against the database

-- Make string columns nullable
ALTER TABLE HEEADSSSAssessments ALTER COLUMN UserId NVARCHAR(450) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN HealthFacility NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN FamilyNo NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN FullName NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN Address NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN ContactNumber NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN Gender NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN HomeEnvironment NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN FamilyRelationship NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN HomeFamilyProblems NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN HomeParentalListening NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN HomeParentalBlame NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN HomeFamilyChanges NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SchoolPerformance NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN CareerPlans NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EducationCurrentlyStudying NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EducationWorking NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EducationSchoolWorkProblems NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EducationBullying NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EducationEmployment NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN DietDescription NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EatingBodyImageSatisfaction NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EatingDisorderedEatingBehaviors NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN EatingWeightComments NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN Hobbies NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN PhysicalActivity NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN ScreenTime NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN ActivitiesParticipation NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN ActivitiesRegularExercise NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN ActivitiesScreenTime NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SubstanceType NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN DrugsTobaccoUse NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN DrugsAlcoholUse NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN DrugsIllicitDrugUse NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN DatingRelationships NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualOrientation NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityBodyConcerns NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityIntimateRelationships NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityPartners NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualitySexualOrientation NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityPregnancy NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualitySTI NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SexualityProtection NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN PersonalStrengths NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SupportSystems NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN CopingMechanisms NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SafetyPhysicalAbuse NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SafetyRelationshipViolence NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SafetyProtectiveGear NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SafetyGunsAtHome NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SuicideDepressionFeelings NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SuicideSelfHarmThoughts NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN SuicideFamilyHistory NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN AssessmentNotes NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN RecommendedActions NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN FollowUpPlan NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN Notes NVARCHAR(MAX) NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN AssessedBy NVARCHAR(MAX) NULL;

-- Make date and integer columns nullable
ALTER TABLE HEEADSSSAssessments ALTER COLUMN Birthday DATETIME NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN Age INT NULL;
ALTER TABLE HEEADSSSAssessments ALTER COLUMN AppointmentId INT NULL;

-- Make UpdatedAt nullable (CreatedAt should remain non-nullable with default)
ALTER TABLE HEEADSSSAssessments ALTER COLUMN UpdatedAt DATETIME NULL; 