CREATE TABLE NCDRiskAssessments (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId NVARCHAR(450) NOT NULL,
    AppointmentId INT NOT NULL,
    AppointmentType NVARCHAR(100) NOT NULL,
    FamilyNo NVARCHAR(50),
    Address NVARCHAR(255),
    Barangay NVARCHAR(100),
    Birthday DATE,
    Telepono NVARCHAR(20),
    Edad INT,
    Kasarian NVARCHAR(10),
    Relihiyon NVARCHAR(50),
    HasDiabetes BIT DEFAULT 0,
    HasHypertension BIT DEFAULT 0,
    HasCancer BIT DEFAULT 0,
    HasCOPD BIT DEFAULT 0,
    HasLungDisease BIT DEFAULT 0,
    HasEyeDisease BIT DEFAULT 0,
    CancerType NVARCHAR(100),
    SmokingStatus NVARCHAR(50),
    AlcoholConsumption NVARCHAR(50),
    HasChestPain BIT DEFAULT 0,
    ChestPainLocation BIT DEFAULT 0,
    ChestPainWhenWalking BIT DEFAULT 0,
    StopsWhenPain BIT DEFAULT 0,
    PainRelievedWithRest BIT DEFAULT 0,
    PainGoneIn10Min BIT DEFAULT 0,
    PainMoreThan30Min BIT DEFAULT 0,
    HasNumbness BIT DEFAULT 0,
    FamilyHasHypertension BIT DEFAULT 0,
    FamilyHasHeartDisease BIT DEFAULT 0,
    FamilyHasStroke BIT DEFAULT 0,
    FamilyHasDiabetes BIT DEFAULT 0,
    FamilyHasCancer BIT DEFAULT 0,
    FamilyHasKidneyDisease BIT DEFAULT 0,
    FamilyHasOtherDisease BIT DEFAULT 0,
    FamilyOtherDiseaseDetails NVARCHAR(MAX),
    EatsVegetables BIT DEFAULT 0,
    EatsFruits BIT DEFAULT 0,
    EatsFish BIT DEFAULT 0,
    EatsMeat BIT DEFAULT 0,
    EatsProcessedFood BIT DEFAULT 0,
    HasHighSaltIntake BIT DEFAULT 0,
    EatsSaltyFood BIT DEFAULT 0,
    EatsSweetFood BIT DEFAULT 0,
    EatsFattyFood BIT DEFAULT 0,
    DrinksAlcohol BIT DEFAULT 0,
    DrinksBeer BIT DEFAULT 0,
    DrinksWine BIT DEFAULT 0,
    DrinksHardLiquor BIT DEFAULT 0,
    IsBingeDrinker BIT DEFAULT 0,
    AlcoholFrequency NVARCHAR(50),
    HasRegularExercise BIT DEFAULT 0,
    HasNoRegularExercise BIT DEFAULT 0,
    ExerciseDuration NVARCHAR(50),
    RiskStatus NVARCHAR(50),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id),
    FOREIGN KEY (AppointmentId) REFERENCES Appointments(Id)
); 