name: Deploy BHCARE to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME: 'bhcare-webapp'   # Change if your app name is different
  AZURE_RESOURCE_GROUP: 'BHcare'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # -------------------------
    # Checkout source code
    # -------------------------
    - name: Checkout code
      uses: actions/checkout@v4
    
    # -------------------------
    # Setup .NET
    # -------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # -------------------------
    # Restore, Build, Test
    # -------------------------
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --logger trx --results-directory ./TestResults
    
    # -------------------------
    # Publish for deployment
    # -------------------------
    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish
    
    # -------------------------
    # Azure Login
    # -------------------------
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # -------------------------
    # Deploy to Azure Web App
    # -------------------------
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        package: ./publish
    
    # -------------------------
    # Configure App Settings
    # -------------------------
    - name: Configure App Settings
      uses: azure/CLI@v2
      with:
        inlineScript: |
          echo "Configuring app settings..."
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --settings \
            "ASPNETCORE_ENVIRONMENT=Production" \
            "EncryptionKey=BHCARE_Production_Encryption_Key_2024_Secure_32Chars" \
            "DataEncryption__Key=BHCARE_Production_DataEncryption_Key_2024_Secure_32Chars" \
            "EmailSettings__SmtpHost=smtp.gmail.com" \
            "EmailSettings__SmtpPort=587" \
            "EmailSettings__SmtpUsername=barangayexample549@gmail.com" \
            "EmailSettings__SmtpPassword=${{ secrets.EMAIL_PASSWORD }}" \
            "EmailSettings__FromEmail=barangayexample549@gmail.com" \
            "EmailSettings__EnableSsl=true"
          echo "App settings configured successfully!"
    
    # -------------------------
    # Configure Connection String
    # -------------------------
    - name: Configure Connection String
      uses: azure/CLI@v2
      with:
        inlineScript: |
          echo "Configuring database connection..."
          az webapp config connection-string set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --connection-string-type SQLServer \
            --settings "DefaultConnection=${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
          echo "Database connection configured!"
    
    # -------------------------
    # Run Database Migrations (if EF Core is used)
    # -------------------------
    - name: Run Database Migrations
      run: |
        echo "Running database migrations..."
        dotnet tool install --global dotnet-ef
        export PATH="$PATH:/home/runner/.dotnet/tools"
        dotnet ef database update --project ./BHCARE.csproj
        echo "Database migrations applied!"
    
    # -------------------------
    # Verify Deployment
    # -------------------------
    - name: Verify Deployment
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # -------------------------
    # Upload Test Results
    # -------------------------
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./TestResults/
